enum GAME_STATE {
	MAIN_MENU,
	OVERWORLD,
	IN_GAME_MENU,//PSIII style menu
	BATTLE,//PSIV style combat
	CUTSCENE,
	TRANSITIONING,
	GAME_OVER
}

enum MENU_PAGE {
	MAIN,
	INVENTORY,
	SKILLS,
	EQUIP,
	STATS,
	ORDER,
	TALK,
	MACRO,
	SETTINGS,
	SAVE,
	QUIT
}

enum BATTLE_PHASE {
	SELECT_COMMAND,
	SELECT_TARGET,
	RUN_MACRO,
	EXECUTE_TURN,
	WIN_LOSS
}

enum TITLE_STAGE {
	SPLASH_1,
	SPLASH_2,
	TITLE_IDLE,//Background showing, waiting for "Press Start"
	MENU_ACTIVE//The actual selectable options appear
}

enum MENU_VARIANT {
		NEW_PLAYER,//only new game and misc 
		RETURNING//allows to load game
}

enum INVENTORY_STATE {
	SELECT_WHO,//"Whose" + party list
	SELECT_ITEM,//"What?" + inventory list
	SELECT_ACTION,//"Use / Give / Toss"
	SELECT_TARGET,//"On Whom?" + party list again
	SELECT_GIVE_TARGET//separate target selection for give
}

enum SUBMENU_HISTORY {
	NONE,
	MAIN,
	INVENTORY_SELECT_WHO,
	INVENTORY_SELECT_ITEM,
	INVENTORY_SELECT_ACTION,
	INVENTORY_SELECT_TARGET,
	STATS_SELECT_WHO,
	STATS_VIEW,
	QUIT_CONFIRM,
	ORDER_SELECT,
	ORDER_CONFIRM,
	INVENTORY_SELECT_GIVE_TARGET,
	EQUIP_SELECT_WHO,
	EQUIP_SELECT_SLOT,
	EQUIP_SELECT_HAND,
	SAVE_SELECT_SLOT,
	SAVE_CONFIRM_OVERWRITE,
	SKILL_SELECT_WHO,
	SKILL_SELECT_WHAT,
	SKILL_SELECT_TARGET//add more later for other sub-menus
}

enum STATS_STATE {
	SELECT_WHO,
	VIEW_STATS
}

enum QUIT_STATE {
	SELECT
}

enum ORDER_STATE {
	SELECT,
	CONFIRM
}

enum EQUIP_STATE {
	SELECT_WHO,
	SELECT_SLOT,
	SELECT_HAND
}

enum SAVE_STATE {
	SELECT_SLOT,
	CONFIRM_OVERWRITE,
	SAVED
}

enum SKILL_STATE {
	SELECT_WHO,
	SELECT_WHAT,
	SELECT_TARGET,
	CANNOT
}